project:
  type: website
  output-dir: docs

website:
  title: "BeeSpatial Tutorial"
  sidebar:
    style: docked
    contents:
      - text: "Welcome"
        file: index.qmd
      - section: "Getting Started"
        contents:
          - introgis.qmd
      - section: "Raster data"
        contents:
          - rasterget.qmd
          - rasterwork.qmd
      - section: "Vector data"
        contents:
          - vectorget.qmd
          - vectorwork.qmd

format:
  html:
    theme: cosmos
    toc: true
