project:
  type: website
  output-dir: docs
  resources:
    - data/cdl_colormap.csv
    - data/McNeil_etal_2020_sites_2018-19.csv

website:
  title: "BeeSpatial Tutorial"
  sidebar:
    style: docked
    contents:
      - text: "Welcome"
        file: index.qmd
      - section: "How to use BeeSpatial"
        contents:
          - BeeSpatialBound.qmd
          - BeeSpatialPts.qmd
      - section: "Working with BeeSpatial data in R"
        contents:
          - introgis.qmd
          - rasterViz.qmd
          - rasterReclass.qmd
          - vectorWork.qmd

format:
  html:
    theme: cosmos
    toc: true
    css: styles.css
