project:
  type: website
  output-dir: docs

website:
  title: "BeeSpatial Tutorial"
  sidebar:
    style: docked
    contents:
      - text: "Welcome"
        file: index.qmd
      - section: "Getting Started"
        contents:
          - introgis.qmd
      - section: "Part 1: Data prep"
        contents:
          - raster.qmd

format:
  html:
    theme: cosmos
    toc: true
