project:
  type: website
  output-dir: docs

website:
  title: "BeeSpatial Tutorial"
  sidebar:
    style: docked
    contents:
      - text: "Welcome"
        file: index.qmd
      - file: introgis.qmd

format:
  html:
    theme: cosmos
    toc: true
